/**
 * Alert message types for the alert-service.
 *
 * The `alerts` Kafka topic is written to by multiple producers:
 *   - environment-service  (temperature / humidity anomalies)
 *   - inventory-service    (pile volume drop alerts)
 *   - …future producers
 *
 * The schema enforces only the fields that every alert must carry.
 * Producer-specific fields are preserved in the `payload` JSONB column so
 * the service can surface them without needing to import each producer's types.
 *
 * Expected DB schema (TimescaleDB):
 *
 *   CREATE TABLE alerts (
 *     id           UUID        NOT NULL,
 *     received_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 *     customer_id  UUID        NOT NULL,
 *     site_id      UUID,
 *     source       TEXT        NOT NULL,  -- Kafka header "service", e.g. "environment-service"
 *     alert_type   TEXT        NOT NULL,  -- e.g. "temperature_high", "pile_volume_drop"
 *     severity     TEXT        NOT NULL CHECK (severity IN ('warning','critical')),
 *     entity_id    TEXT,                  -- sensorId, pileId, etc.
 *     entity_type  TEXT,                  -- sensor_type, material_type, etc.
 *     message      TEXT        NOT NULL,
 *     payload      JSONB       NOT NULL,  -- full original message
 *     PRIMARY KEY (id, received_at)       -- compound PK for hypertable
 *   );
 *
 *   SELECT create_hypertable('alerts', 'received_at', if_not_exists => TRUE);
 *
 *   CREATE INDEX ON alerts (customer_id, received_at DESC);
 *   CREATE INDEX ON alerts (customer_id, site_id, received_at DESC);
 *   CREATE INDEX ON alerts (customer_id, severity, received_at DESC);
 *   CREATE INDEX ON alerts (customer_id, alert_type, received_at DESC);
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Severity constants
// ---------------------------------------------------------------------------

export const ALERT_SEVERITIES = ["warning", "critical"] as const;
export type AlertSeverity = typeof ALERT_SEVERITIES[number];

// ---------------------------------------------------------------------------
// Inbound Kafka payload schema
//
// Validates only the minimum required fields.  Extra properties pass through
// and are stored in the JSONB payload column.
// ---------------------------------------------------------------------------

export const alertPayloadSchema = z.object({
  /** UUID generated by the producer — used for idempotent inserts. */
  id: z.string().uuid(),

  /** Alert type identifier, e.g. "temperature_high", "pile_volume_drop". */
  type: z.string().min(1),

  /** Severity level. */
  severity: z.enum(ALERT_SEVERITIES),

  /**
   * Tenant identifier.  Must match the JWT claim used by the REST API.
   * Producers embed this in the payload and in Kafka headers.
   */
  customerId: z.string().uuid(),

  /**
   * Site identifier — present for most but not guaranteed for all alert types.
   */
  siteId: z.string().uuid().optional(),

  /**
   * The entity that triggered the alert.
   * For environment alerts: sensorId.
   * For inventory alerts:   pileId.
   */
  entityId: z.string().optional(),

  /**
   * The type/class of the entity, e.g. "combined", "bulk_grain".
   * Used for display and filtering.
   */
  entityType: z.string().optional(),

  /** Human-readable alert description. */
  message: z.string().min(1),

  /**
   * ISO 8601 timestamp of when the alert was detected at the source.
   * Distinct from received_at (when this service ingested it).
   */
  detectedAt: z.string().datetime(),
}).passthrough(); // preserve producer-specific fields

export type AlertPayload = z.infer<typeof alertPayloadSchema>;

// ---------------------------------------------------------------------------
// Domain type — a persisted alert record
// ---------------------------------------------------------------------------

export interface Alert {
  id:          string;
  receivedAt:  Date;
  customerId:  string;
  siteId:      string | null;
  source:      string;
  alertType:   string;
  severity:    AlertSeverity;
  entityId:    string | null;
  entityType:  string | null;
  message:     string;
  /** Full original Kafka payload, preserved for downstream consumers. */
  payload:     Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// DB row (snake_case, JSONB arrives as parsed object from pg)
// ---------------------------------------------------------------------------

export interface AlertRow {
  id:          string;
  received_at: Date;
  customer_id: string;
  site_id:     string | null;
  source:      string;
  alert_type:  string;
  severity:    string;
  entity_id:   string | null;
  entity_type: string | null;
  message:     string;
  payload:     Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Kafka message header helpers
// ---------------------------------------------------------------------------

/**
 * Headers the environment-service attaches to every alert message.
 * Other producers should follow the same convention.
 */
export interface AlertHeaders {
  "content-type"?: string;
  "alert-type"?:   string;
  "severity"?:     string;
  "customer-id"?:  string;
  "service"?:      string;
}

/** Extract a UTF-8 string from a KafkaJS header value (Buffer | string | undefined). */
export function headerToString(value: Buffer | string | undefined): string | undefined {
  if (value === undefined) return undefined;
  return Buffer.isBuffer(value) ? value.toString("utf8") : value;
}
