apiVersion: v1
kind: ServiceAccount
metadata:
  name: alert-service
  namespace: warehouse
  labels:
    app: alert-service
    app.kubernetes.io/part-of: warehouse-platform
---
apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: warehouse
  labels:
    app: alert-service
    app.kubernetes.io/name: alert-service
    app.kubernetes.io/part-of: warehouse-platform
spec:
  type: ClusterIP
  selector:
    app: alert-service
  ports:
    - name: http
      port: 3004
      targetPort: http
      protocol: TCP
