apiVersion: v1
kind: ServiceAccount
metadata:
  name: environment-service
  namespace: warehouse
  labels:
    app: environment-service
    app.kubernetes.io/part-of: warehouse-platform
---
apiVersion: v1
kind: Service
metadata:
  name: environment-service
  namespace: warehouse
  labels:
    app: environment-service
    app.kubernetes.io/name: environment-service
    app.kubernetes.io/part-of: warehouse-platform
spec:
  type: ClusterIP
  selector:
    app: environment-service
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
