/**
 * Request ID middleware.
 *
 * Assigns a unique identifier to every request so log lines from the
 * gateway and all upstream services can be correlated.
 *
 * Priority order:
 *   1. X-Request-Id header supplied by the client (forwarded as-is)
 *   2. X-Correlation-Id header (alternative name used by some clients)
 *   3. Fresh UUIDv4 generated by the gateway
 *
 * The chosen ID is:
 *   • Stored in res.locals.requestId for middleware access
 *   • Written back into req.headers so http-proxy-middleware forwards it
 *   • Added to the response as X-Request-Id
 */

import { RequestHandler } from "express";
import { v4 as uuidv4 } from "uuid";

export const requestId: RequestHandler = (req, res, next): void => {
  const id =
    (req.headers["x-request-id"] as string | undefined) ||
    (req.headers["x-correlation-id"] as string | undefined) ||
    uuidv4();

  // Normalise: store on locals and ensure the header is set for the proxy
  res.locals["requestId"] = id;
  req.headers["x-request-id"] = id;
  res.setHeader("X-Request-Id", id);

  next();
};
